name: metro_chat
description: "Encrypted peer to peer retro themed chat app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.39
  permission_handler: ^11.3.1
  go_router: ^14.2.1
  flutter_svg: ^2.0.10+1
  flutter_bloc: ^8.1.6
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  assets:
    - assets/Sounds/splash_screen_sound_effect.mp3
    - assets/Icons/
  fonts:
    - family: GoldenAgeShad
      fonts:
        - asset: assets/Fonts/Golden Age Shad.ttf
    - family: Monoton
      fonts:
        - asset: assets/Fonts/Monoton-Regular.ttf
    - family: Pixellari
      fonts:
        - asset: assets/Fonts/Pixellari.ttf
    - family: RetroGaming
      fonts:
        - asset: assets/Fonts/Retro Gaming.ttf

  uses-material-design: true
