// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqH2dLoDUXxznL52uTSRpYJIi9W_FUe6E',
    appId: '1:658327615717:web:a5fe4e4d57a2ad6d68bc0c',
    messagingSenderId: '658327615717',
    projectId: 'metro-chat-ed6a0',
    authDomain: 'metro-chat-ed6a0.firebaseapp.com',
    storageBucket: 'metro-chat-ed6a0.appspot.com',
    measurementId: 'G-K4NH7438CQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJqT-lKXhInNqTx-OHWPdJna-yfzHf9ec',
    appId: '1:658327615717:android:b3817524d4b288a968bc0c',
    messagingSenderId: '658327615717',
    projectId: 'metro-chat-ed6a0',
    storageBucket: 'metro-chat-ed6a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACUA_pzANfopinU8WgBOmkwWDB1O6W1q8',
    appId: '1:658327615717:ios:aea77d820fb8aa0068bc0c',
    messagingSenderId: '658327615717',
    projectId: 'metro-chat-ed6a0',
    storageBucket: 'metro-chat-ed6a0.appspot.com',
    iosBundleId: 'com.example.metroChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACUA_pzANfopinU8WgBOmkwWDB1O6W1q8',
    appId: '1:658327615717:ios:aea77d820fb8aa0068bc0c',
    messagingSenderId: '658327615717',
    projectId: 'metro-chat-ed6a0',
    storageBucket: 'metro-chat-ed6a0.appspot.com',
    iosBundleId: 'com.example.metroChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqH2dLoDUXxznL52uTSRpYJIi9W_FUe6E',
    appId: '1:658327615717:web:c48494fdad52bc9e68bc0c',
    messagingSenderId: '658327615717',
    projectId: 'metro-chat-ed6a0',
    authDomain: 'metro-chat-ed6a0.firebaseapp.com',
    storageBucket: 'metro-chat-ed6a0.appspot.com',
    measurementId: 'G-KDJ60JV9T6',
  );

}